### PR TITLE
Create README.md for COO

### PR DESCRIPTION
**Pull request by prkrtg**

### CODE REVIEW

**Review by scizen9 — APPROVED** [review]
Looks good!

**Review by astronomerdave — APPROVED** [review]

**Comment by drriddle** [comment]
This should be written from the perspective of a neophyte user using this for the first time.  More detail in the steps required to do things.  People will learn, but the first time they will barely know how to navigate the website, much less add a pull request or create a branch.

**Review by mikelangmayr — COMMENTED** [review]
Looks great! 
Does it make sense to share the jira link? If one doesn't have access they won't see anything there

**Comment by prkrtg** [comment]
> This should be written from the perspective of a neophyte user using this for the first time. More detail in the steps required to do things. People will learn, but the first time they will barely know how to navigate the website, much less add a pull request or create a branch.

@drriddle Updated the README for newcomers

**Pull request merged**
